const movies = [
  "Moana",
  "Sing",
  "Sing 2",
  "Incredibles",
  "Luca",
  "Pocahantas",
  "Cinderella",
  "Beauty and the beast",
  "Frozen",
  "Frozen 2",
  "Snow white and the seven dwarfs",
  "Encanto",
  "Grinch",
  "Monsters University",
  "Wild hearts cannot be broken",
  "Home alone",
  "Home alone 2",
  "Finding Dory",
  "Wreck it Ralph",
  "Bolt",
  "Tangled",
  "Raya the last dragon",
  "Zootopia",
  "Cars",
  "Coco",
  "Onward",
  "Ice Age",
  "Inside Out",
  "Toy Story",
  "Up",
  "Mulan",
  "Tarzan",
  "Aladdin",
  "Hercules",
  "Peter Pan",
  "Sleeping Beauty"
];

export default movies;
